sudo yum update -y
sudo amazon-linux-extras install java-openjdk11 -y
sudo amazon-linux-extras install java-openjdk11 -y
sudo wget -O /etc/yum.repos.d/jenkins.repo     https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum install jenkins git -y
systemctl enable jenkins
systemctl start jenkins
systemctl status jenkins.service
sudo journalctl -xeu jenkins.service | tail -n 200
java -version || true
which java || true
which java
sudo yum makecache fast
if sudo amazon-linux-extras list | grep -q 'java-openjdk11'; then   echo "Using amazon-linux-extras to install java-11-openjdk";  sudo amazon-linux-extras enable java-openjdk11
sudo amazon-linux-extras enable java-openjdk11
sudo yum install -y java-11-openjdk-devel
sudo mkdir -p /opt/java
cd /opt/java
sudo curl -LO https://github.com/adoptium/temurin11-binaries/releases/latest/download/OpenJDK11U-jdk_x64_linux_hotspot_latest.tar.gz
sudo tar -xzf OpenJDK11U-jdk_x64_linux_hotspot_latest.tar.gz
sudo alternatives --install /usr/bin/java java /opt/java/<jdk-folder>/bin/java 200000
sudo rpm --import https://yum.corretto.aws/corretto.key
sudo curl -sSL https://yum.corretto.aws/corretto.repo -o /etc/yum.repos.d/corretto.repo
sudo yum makecache fast
sudo yum clean all
sudo yum makecache
sudo yum install -y java-11-amazon-corretto-devel
java -version || tru
JAVA_BIN=$(readlink -f "$(which java)")
JAVA_HOME=$(dirname $(dirname "$JAVA_BIN"))
echo "Detected JAVA_BIN=$JAVA_BIN"
echo "Detected JAVA_HOME=$JAVA_HOME"
sudo cp /etc/sysconfig/jenkins /etc/sysconfig/jenkins.bak.$(date +%F_%T)
sudo systemctl daemon-reload
systemctl enable jenkins
systemctl start jenkins
systemctl restart jenkins
java -version
sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum clean all
sudo yum makecache
sudo yum install -y jenkins
ls -l /etc/sysconfig/jenkins
sed -n '1,200p' /etc/sysconfig/jenkins
JAVA_BIN=$(readlink -f "$(which java)")
if [ -z "$JAVA_BIN" ]; then   echo "ERROR: java binary not found in PATH; run 'java -version' first.";   exit 1; fi
JAVA_HOME=$(dirname $(dirname "$JAVA_BIN"))
echo "Detected JAVA_BIN=$JAVA_BIN"
echo "Detected JAVA_HOME=$JAVA_HOME"
echo
if [ -f /etc/sysconfig/jenkins ]; then   sudo cp /etc/sysconfig/jenkins /etc/sysconfig/jenkins.bak.$(date +%F_%T);   echo "Backed up existing /etc/sysconfig/jenkins"; fi
sudo bash -c "cat > /etc/sysconfig/jenkins <<'EOF'

if [ -f /etc/sysconfig/jenkins ]; then   sudo cp /etc/sysconfig/jenkins /etc/sysconfig/jenkins.bak.$(date +%F_%T);   echo "Backed up existing /etc/sysconfig/jenkins"; fi
sudo bash -c "cat > /etc/sysconfig/jenkins <<'EOF'
# Jenkins environment file generated by assistant
# JAVA settings
JAVA_HOME=$JAVA_HOME
JENKINS_JAVA_CMD=$JAVA_BIN

# Optional JVM options: adjust if instance has low memory
# JENKINS_JAVA_OPTIONS='-Djava.awt.headless=true -Xmx1024m'
EOF"
echo "/etc/sysconfig/jenkins created. Showing contents:"
sudo sed -n '1,200p' /etc/sysconfig/jenkins
echo
sudo systemctl daemon-reload
sudo systemctl enable --now jenkins || true
sudo systemctl enable --now jenkins || true
sleep 2
echo "---- current service status ----"
sudo systemctl status jenkins.service --no-pager
echo
echo "---- last 200 journal lines for jenkins ----"
sudo journalctl -xeu jenkins.service | tail -n 200
# refresh yum metadata
sudo yum clean all
sudo yum makecache
# install Corretto 17
sudo yum install -y java-17-amazon-corretto-devel
# verify
java -version
which java
readlink -f $(which java) || true
# detect java
JAVA_BIN=$(readlink -f "$(which java)")
JAVA_HOME=$(dirname $(dirname "$JAVA_BIN"))
echo "JAVA_BIN=$JAVA_BIN"
echo "JAVA_HOME=$JAVA_HOME"
# backup and update config
sudo cp /etc/sysconfig/jenkins /etc/sysconfig/jenkins.bak.$(date +%F_%T) 2>/dev/null || true
sudo sed -i "s|^JAVA_HOME=.*|JAVA_HOME=$JAVA_HOME|" /etc/sysconfig/jenkins 2>/dev/null || true
sudo sed -i "s|^JENKINS_JAVA_CMD=.*|JENKINS_JAVA_CMD=$JAVA_BIN|" /etc/sysconfig/jenkins 2>/dev/null || true
# if those lines were absent, append
sudo bash -c "grep -q '^JAVA_HOME=' /etc/sysconfig/jenkins || echo \"JAVA_HOME=$JAVA_HOME\" >> /etc/sysconfig/jenkins"
sudo bash -c "grep -q '^JENKINS_JAVA_CMD=' /etc/sysconfig/jenkins || echo \"JENKINS_JAVA_CMD=$JAVA_BIN\" >> /etc/sysconfig/jenkins"
# show file head
sudo sed -n '1,120p' /etc/sysconfig/jenkins
sudo systemctl daemon-reload
sudo systemctl restart jenkins
sudo systemctl status jenkins.service --no-pager
sudo journalctl -xeu jenkins.service | tail -n 200
sudo systemctl restart jenkins
sudo systemctl status jenkins
sudo cat /var/lib/jenkins/secrets/initialAdminPassword
